title: "Tobis Kochbuch"
description: "Online-Kochbuch"
markdown: kramdown

# WICHTIG: Repo-Name hier eintragen (ohne Domain)
baseurl: "/Kochen"
url: "https://tbsxxl.github.io"

collections:
  recipes:
    output: true
    permalink: /rezepte/:name/

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe
