title: "Tobis Kochbuch"
description: "Online-Kochbuch"

url: "https://tbsxxl.github.io"
baseurl: "/Kochen"

markdown: kramdown

collections:
  recipes:
    output: true
    permalink: /rezepte/:name/

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe
